# Servicios externos del aplicativo
version: "3.7"

services:   
  # 2.	Rabbitmq
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: always
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:2567"


  # 1.	Ocrmypdf
  ocrmypdf:    
    image: jbarlow83/ocrmypdf:latest
    container_name: ocrmypdf
    restart: always
    ports:
      - "5000:5000"
    entrypoint: ["python3", "webservice.py"]
  
    
  # 3. redismod (RediSearch, RedisGraph, RedisTimeSeries, RedisAI, RedisJSON, RedisBloom, RedisGears)
  redis:    
    image: redislabs/redismod:latest
    container_name: redismod
    restart: always
    privileged: true       
    ports:
      - "6379:6379"
    volumes:
      - "/mnt/e/docker_data/redis_data:/data" 

          
  # 4. Elasticsearch 
  elastic:    
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3
    container_name: elastic
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
       - node.name=es_desarrollo_01
       - cluster.name=cluster_desarrollo
       - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
       - xpack.security.enabled=false
       - xpack.ml.enabled=false
       - xpack.watcher.enabled=false
       - discovery.type=single-node
       - path.data=/usr/share/elasticsearch/data
       - path.logs=/usr/share/elasticsearch/logs
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "/mnt/e/docker_data/elastic_data/data:/usr/share/elasticsearch/data"
      - "/mnt/e/docker_data/elastic_data/logs:/usr/share/elasticsearch/logs"     

        
  # 5. Tika
  tika:
    image: logicalspark/docker-tikaserver:latest
    container_name: tika
    restart: always
    ports:
      - '9998:9998'


  # 6. Arangodb
  #arangodb:
  #  image: arangodb:latest
  #  container_name: arangodb
  #  restart: always
  #  environment:
  #    ARANGO_ROOT_PASSWORD: rootpassword
  #  ports:
  #    - 8529:8529
  #  volumes:
  #    - "/mnt/e/docker_data/arangodb_data/data:/var/lib/arangodb3"
  #    - "/mnt/e/docker_data/arangodb_data/apps:/var/lib/arangodb3-apps"

  
  #################    
  # 7. Onlyoffice #
  #################
  onlyoffice-document-server:    
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice-document-server
    stdin_open: true
    tty: true
    restart: always
    ports:
      - '80:80'
      - '443:443'


  ######################
  # 8. Camunda version #
  ######################
  camunda:
    image: camunda/camunda-bpm-platform:latest
    container_name: camunda
    ports:
      - "3600:8080"
    restart: always
    
  
  ###################################
  # 9. Minio almacenador de objetos #
  ###################################
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    volumes:
      - "/mnt/e/docker_data/openio/data:/data"
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  
  #jodconverter:    
  #  image: eugenmayer/jodconverter:rest
  #  container_name: jodconverter
  #  #networks:
  #  #  - activedocument
  #  restart: always
  #  ports:
  #    - "8080:8080"